#!/usr/bin/env python3
"""Create an empty or illustrative Semantic Decision Bundle."""

from __future__ import annotations

import argparse
import copy
import json
import sys
from pathlib import Path
from typing import Any

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import init_action_bundle  # noqa: E402


SEMANTIC_FILES = [
    "material_manifest.yaml",
    "semantic_ir.yaml",
    "judgment_registry.yaml",
    "semantic_links.yaml",
]


def example_bundle() -> dict[str, Any]:
    bundle = copy.deepcopy(init_action_bundle.example_bundle())
    bundle["evidence_ledger.jsonl"].append(
        {
            "evidence_id": "hypothesis_failure_tone",
            "source_id": "analysis:failure-tone",
            "source_type": "analysis",
            "locator": "analysis:failure-tone",
            "claim": "Failure wording may indicate whether a problem is transient.",
            "grade": "hypothetical",
            "observed_at": None,
            "notes": "Candidate evidence only; forbidden for reviewed judgments.",
        }
    )
    bundle["decision_surfaces.yaml"]["decision_surfaces"][0]["supporting_judgments"] = [
        "failure_is_transient"
    ]
    bundle["coverage_report.md"] = (
        "# Coverage report\n\n"
        "Semantic example generated by init_semantic_bundle.py.\n\n"
        "## Inspected sources\n- SOP\n- Runtime traces\n- Code binding\n\n"
        "## Semantic coverage\n"
        "- One condition and one semantic property\n"
        "- One reviewed Noul supporting one production action surface\n"
        "- Source-to-concept-to-judgment-to-surface-to-action links\n\n"
        "## Known blind spots\n"
        "- No live permission system was inspected.\n"
        "- The supporting judgment has not been calibrated on trusted labels.\n"
    )
    source_ids = sorted({item["source_id"] for item in bundle["evidence_ledger.jsonl"]})
    bundle.update(
        {
            "material_manifest.yaml": {
                "schema_version": "2.0",
                "system_id": "validation_example",
                "scope": "Choose the next action after a validation failure.",
                "sources": [
                    {
                        "source_id": source_id,
                        "kind": (
                            "sop"
                            if source_id.startswith("docs/")
                            else "code"
                            if source_id.endswith(".py")
                            else "analysis"
                            if source_id.startswith("analysis:")
                            else "trace"
                        ),
                        "locator": source_id,
                        "authority": "contextual" if source_id.startswith("analysis:") else "operational",
                        "included": True,
                    }
                    for source_id in source_ids
                ],
            },
            "semantic_ir.yaml": {
                "schema_version": "2.0",
                "system_id": "validation_example",
                "concepts": [
                    {
                        "concept_id": "validation_failure",
                        "kind": "condition",
                        "description": "A completed validation run that did not succeed.",
                        "observable": True,
                        "value_type": "object",
                        "evidence_refs": ["trace_failed_01"],
                    },
                    {
                        "concept_id": "failure_transience",
                        "kind": "semantic_property",
                        "description": "Whether the observed failure is likely temporary rather than structural.",
                        "observable": False,
                        "value_type": "probability",
                        "evidence_refs": ["runbook_retry", "trace_retry_01"],
                    },
                ],
                "relations": [
                    {
                        "relation_id": "failure_has_transience",
                        "subject_id": "validation_failure",
                        "predicate": "has_semantic_property",
                        "object_id": "failure_transience",
                        "evidence_refs": ["runbook_retry", "trace_retry_01"],
                    }
                ],
            },
            "judgment_registry.yaml": {
                "schema_version": "2.0",
                "system_id": "validation_example",
                "families": [
                    {
                        "family_id": "condition_supports_action",
                        "type": "noul",
                        "instructions_template": "Does {condition} support choosing {action} in `context`?",
                        "parameters": ["condition", "action"],
                        "purpose": "Generate evidence features for bounded action selection.",
                        "maturity": "candidate",
                        "evidence_refs": ["runbook_retry"],
                    }
                ],
                "judgments": [
                    {
                        "judgment_id": "failure_is_transient",
                        "family_id": "condition_supports_action",
                        "type": "noul",
                        "instructions": "Does `context.error` indicate a transient failure that may succeed if retried?",
                        "criteria": {
                            "true": "The evidence indicates a temporary timeout, unavailable dependency, or other retryable condition.",
                            "false": "The evidence indicates a deterministic schema, policy, or data error, or is insufficient.",
                        },
                        "state_paths": ["context.error"],
                        "activate_when": ["validation_status == 'failed'"],
                        "surface_ids": ["resolve_validation_failure"],
                        "purpose": "Provide an inspectable semantic feature for the final action choice.",
                        "maturity": "reviewed",
                        "evidence_refs": ["runbook_retry", "trace_retry_01"],
                    }
                ],
            },
            "semantic_links.yaml": {
                "schema_version": "2.0",
                "system_id": "validation_example",
                "links": [
                    {
                        "link_id": "source_to_failure_concept",
                        "from": {"kind": "source", "id": "docs/validation.md#retry"},
                        "to": {"kind": "concept", "id": "failure_transience"},
                        "relation": "supports",
                        "evidence_refs": ["runbook_retry"],
                    },
                    {
                        "link_id": "concept_to_transience_judgment",
                        "from": {"kind": "concept", "id": "failure_transience"},
                        "to": {"kind": "judgment", "id": "failure_is_transient"},
                        "relation": "measured_by",
                        "evidence_refs": ["runbook_retry", "trace_retry_01"],
                    },
                    {
                        "link_id": "judgment_to_surface",
                        "from": {"kind": "judgment", "id": "failure_is_transient"},
                        "to": {"kind": "surface", "id": "resolve_validation_failure"},
                        "relation": "informs",
                        "evidence_refs": ["runbook_retry", "trace_retry_01"],
                    },
                    {
                        "link_id": "surface_to_retry",
                        "from": {"kind": "surface", "id": "resolve_validation_failure"},
                        "to": {"kind": "action", "id": "retry"},
                        "relation": "offers",
                        "evidence_refs": ["trace_retry_01"],
                    },
                ],
            },
        }
    )
    return bundle


def empty_bundle() -> dict[str, Any]:
    bundle = init_action_bundle.empty_bundle()
    bundle.update(
        {
            "material_manifest.yaml": {
                "schema_version": "2.0",
                "system_id": "unconfigured_system",
                "scope": None,
                "sources": [],
            },
            "semantic_ir.yaml": {
                "schema_version": "2.0",
                "system_id": "unconfigured_system",
                "concepts": [],
                "relations": [],
            },
            "judgment_registry.yaml": {
                "schema_version": "2.0",
                "system_id": "unconfigured_system",
                "families": [],
                "judgments": [],
            },
            "semantic_links.yaml": {
                "schema_version": "2.0",
                "system_id": "unconfigured_system",
                "links": [],
            },
        }
    )
    return bundle


def write_bundle(path: Path, bundle: dict[str, Any], force: bool) -> None:
    path.mkdir(parents=True, exist_ok=True)
    existing = [path / name for name in (*init_action_bundle.FILES, *SEMANTIC_FILES) if (path / name).exists()]
    if existing and not force:
        names = ", ".join(item.name for item in existing)
        raise SystemExit(f"Refusing to overwrite existing files: {names}. Use --force.")
    for name, value in bundle.items():
        target = path / name
        if name.endswith(".yaml"):
            target.write_text(yaml.safe_dump(value, sort_keys=False, allow_unicode=True), encoding="utf-8")
        elif name.endswith(".jsonl"):
            target.write_text("".join(json.dumps(item, ensure_ascii=False) + "\n" for item in value), encoding="utf-8")
        else:
            target.write_text(value, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", type=Path)
    parser.add_argument("--example", action="store_true", help="write a validated semantic example")
    parser.add_argument("--force", action="store_true", help="overwrite bundle files")
    args = parser.parse_args()
    write_bundle(args.path, example_bundle() if args.example else empty_bundle(), args.force)
    print(f"created {args.path} ({'example' if args.example else 'empty semantic bundle'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
